# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=40)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "verbose_name": "evento de auditoría",
                "verbose_name_plural": "eventos de auditoría",
                "db_table": "audit_events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
