# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditoria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="auditoria_entidad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["timestamp"], name="auditoria_fecha_idx"),
        ),
    ]
