# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campo", "0001_initial"),
        ("revision", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "phone_e164",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+[1-9]\\d{7,14}$",
                                "Usa el formato internacional, p. ej. +51987654321.",
                            )
                        ],
                        verbose_name="celular (E.164)",
                    ),
                ),
                (
                    "role_label",
                    models.CharField(
                        choices=[
                            ("JEFE_FUNDO", "Jefe de fundo"),
                            ("SUPERVISOR_ZONA", "Supervisor de zona"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=16,
                        verbose_name="función",
                    ),
                ),
                (
                    "opt_in_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que aceptó recibir avisos",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lots",
                    models.ManyToManyField(
                        blank=True,
                        db_table="notification_recipient_lots",
                        help_text="Vacío = todos los lotes",
                        related_name="+",
                        to="campo.fieldlot",
                        verbose_name="lotes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta de la web con la que abre el enlace del caso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cuenta de la web",
                    ),
                ),
            ],
            options={
                "verbose_name": "destinatario",
                "db_table": "notification_recipients",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(default="WHATSAPP", max_length=10)),
                (
                    "kind",
                    models.CharField(
                        choices=[("CASO_CONFIRMADO", "Caso confirmado")],
                        default="CASO_CONFIRMADO",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=150)),
                ("recipient_phone", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("PENDIENTE_ENVIO", "Pendiente de envío"),
                            ("ENVIADO", "Enviado"),
                            ("ERROR_ENVIO", "Error de envío"),
                        ],
                        default="PENDIENTE_ENVIO",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=80)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="revision.case",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="revision.humanreview",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notificaciones.notificationrecipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "aviso",
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="aviso_cola_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review", "recipient"), name="aviso_unico_por_decision"
                    )
                ],
            },
        ),
    ]
