# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('recipient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone_e164', models.CharField(max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_recipients', to='monitoreo.lot')),
            ],
            options={
                'db_table': 'notification_recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TOMADA', 'Tomada'), ('ENVIADA', 'Enviada'), ('ERROR_REINTENTABLE', 'Error reintentable'), ('ERROR_FINAL', 'Error final'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='revision.case')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.notificationrecipient')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='idx_notification_queue')],
            },
        ),
    ]
