# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0002_restricciones_check"),
        ("notificaciones", "0001_initial"),
        ("revision", "0002_restricciones_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["CASO_CONFIRMADO"])),
                name="notifications_kind_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["NO_APLICA", "PENDIENTE_ENVIO", "ENVIADO", "ERROR_ENVIO"],
                    )
                ),
                name="notifications_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationrecipient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role_label__in", ["JEFE_FUNDO", "SUPERVISOR_ZONA", "OTRO"])
                ),
                name="notification_recipients_role_label_valido",
            ),
        ),
    ]
