# Generated by Django 5.2.17 on 2026-10-08 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0002_restricciones_check"),
        ("revision", "0002_restricciones_check"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notifications_kind_valido",
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CASO_CONFIRMADO", "Caso confirmado"),
                    ("CASO_CONFIRMADO_IA", "Confirmado por IA"),
                ],
                default="CASO_CONFIRMADO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="revision.humanreview",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review__isnull", True)),
                fields=("case", "recipient"),
                name="aviso_ia_unico_por_caso",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["CASO_CONFIRMADO", "CASO_CONFIRMADO_IA"])
                ),
                name="notifications_kind_valido",
            ),
        ),
    ]
