# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuentas", "0001_initial"),
        ("monitoreo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Capture",
            fields=[
                ("capture_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "lateral_code",
                    models.CharField(
                        choices=[
                            ("LATERAL_A", "Lateral A"),
                            ("LATERAL_B", "Lateral B"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "camera_role",
                    models.CharField(
                        choices=[("CAMERA_1", "Cámara 1"), ("CAMERA_2", "Cámara 2")],
                        max_length=10,
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("md5", models.CharField(max_length=32)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("UTILIZABLE", "Utilizable"),
                            ("REPETIR_NITIDEZ", "Repetir por nitidez"),
                            ("REPETIR_EXPOSICION", "Repetir por exposición"),
                            ("ERROR_CAMARA", "Error de cámara"),
                            (
                                "PENDIENTE_REVISION_TECNICA",
                                "Pendiente de revisión técnica",
                            ),
                        ],
                        max_length=28,
                    ),
                ),
                ("retake_context", models.JSONField(blank=True, null=True)),
                ("app_version", models.CharField(max_length=40)),
                ("cloudinary_public_id", models.CharField(max_length=255, unique=True)),
                ("cloudinary_version", models.BigIntegerField()),
                ("cloudinary_bytes", models.PositiveBigIntegerField()),
                ("cloudinary_format", models.CharField(blank=True, max_length=10)),
                (
                    "cloudinary_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cloudinary_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "camera_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cuentas.device",
                    ),
                ),
                (
                    "monitoring_pass",
                    models.ForeignKey(
                        db_column="pass_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captures",
                        to="monitoreo.monitoringpass",
                    ),
                ),
                (
                    "operator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces_capture",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="replaced_by",
                        to="evidencias.capture",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captures",
                        to="monitoreo.capturesequence",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captures",
                        to="monitoreo.monitoringsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "captura",
                "db_table": "captures",
            },
        ),
        migrations.CreateModel(
            name="QualityResult",
            fields=[
                (
                    "capture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="quality",
                        serialize=False,
                        to="evidencias.capture",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UTILIZABLE", "Utilizable"),
                            ("REPETIR_NITIDEZ", "Repetir por nitidez"),
                            ("REPETIR_EXPOSICION", "Repetir por exposición"),
                            ("ERROR_CAMARA", "Error de cámara"),
                            (
                                "PENDIENTE_REVISION_TECNICA",
                                "Pendiente de revisión técnica",
                            ),
                        ],
                        max_length=28,
                    ),
                ),
                ("reasons", models.JSONField(default=list)),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("profile_version", models.CharField(max_length=20)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "quality_results",
            },
        ),
        migrations.AddIndex(
            model_name="capture",
            index=models.Index(fields=["captured_at"], name="captura_fecha_idx"),
        ),
    ]
