# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('capture_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('marker_code', models.CharField(blank=True, max_length=80)),
                ('quality_status', models.CharField(choices=[('UTILIZABLE', 'Utilizable'), ('RECHAZADA', 'Rechazada'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('cloudinary_public_id', models.CharField(max_length=255, unique=True)),
                ('cloudinary_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cloudinary_bytes', models.PositiveIntegerField(default=0)),
                ('cloudinary_format', models.CharField(default='jpg', max_length=20)),
                ('cloudinary_width', models.PositiveIntegerField(blank=True, null=True)),
                ('cloudinary_height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='cuentas.mobiledevice')),
                ('pass_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='monitoreo.fieldpass')),
                ('replaces_capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidencias.capture')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='monitoreo.croprow')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='monitoreo.monitoringsession')),
            ],
            options={
                'db_table': 'captures',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_result', to='evidencias.capture')),
            ],
            options={
                'db_table': 'quality_results',
            },
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['quality_status', '-captured_at'], name='idx_capture_quality_time'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_capture_location'),
        ),
    ]
