# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_restricciones_check"),
        ("evidencias", "0001_initial"),
        ("monitoreo", "0002_restricciones_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="capture",
            constraint=models.CheckConstraint(
                condition=models.Q(("lateral_code__in", ["LATERAL_A", "LATERAL_B"])),
                name="captures_lateral_code_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capture",
            constraint=models.CheckConstraint(
                condition=models.Q(("camera_role__in", ["CAMERA_1", "CAMERA_2"])),
                name="captures_camera_role_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capture",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quality_status__in",
                        [
                            "UTILIZABLE",
                            "REPETIR_NITIDEZ",
                            "REPETIR_EXPOSICION",
                            "ERROR_CAMARA",
                            "PENDIENTE_REVISION_TECNICA",
                        ],
                    )
                ),
                name="captures_quality_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "UTILIZABLE",
                            "REPETIR_NITIDEZ",
                            "REPETIR_EXPOSICION",
                            "ERROR_CAMARA",
                            "PENDIENTE_REVISION_TECNICA",
                        ],
                    )
                ),
                name="quality_results_status_valido",
            ),
        ),
    ]
