# Generated by Django 5.2.17 on 2026-10-09 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0002_restricciones_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedSession",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión eliminada",
                "verbose_name_plural": "sesiones eliminadas",
                "db_table": "deleted_sessions",
            },
        ),
        migrations.CreateModel(
            name="DeletedCapture",
            fields=[
                ("capture_id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("cloudinary_public_id", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SESION", "Sesión eliminada"),
                            ("DESCARTADAS", "Limpieza de fotos descartadas por la IA"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("cloud_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cloud_error", models.CharField(blank=True, max_length=300)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "foto eliminada",
                "verbose_name_plural": "fotos eliminadas",
                "db_table": "deleted_captures",
                "indexes": [
                    models.Index(fields=["cloud_deleted_at"], name="borradas_nube_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reason__in", ["SESION", "DESCARTADAS"])),
                        name="deleted_captures_reason_valido",
                    )
                ],
            },
        ),
    ]
