# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform__in", ["android", "ios"])),
                name="devices_platform_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="passwordresetrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDIENTE", "ATENDIDA", "DESCARTADA"])
                ),
                name="password_reset_requests_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["PENDIENTE_APROBACION", "ACTIVO", "RECHAZADO", "BLOQUEADO"],
                    )
                ),
                name="users_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        [
                            "ADMINISTRADOR",
                            "OPERADOR_CAMPO",
                            "ESPECIALISTA_FITOSANITARIO",
                            "SUPERVISOR",
                        ],
                    )
                ),
                name="user_roles_role_valido",
            ),
        ),
    ]
