# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldLot",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("geometry", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "lote",
                "db_table": "field_lots",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="QualityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("params", models.JSONField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "perfil de calidad",
                "verbose_name_plural": "perfiles de calidad",
                "db_table": "quality_profiles",
            },
        ),
        migrations.CreateModel(
            name="FieldRow",
            fields=[
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("plant_count", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="campo.fieldlot",
                    ),
                ),
            ],
            options={
                "verbose_name": "hilera",
                "db_table": "field_rows",
                "ordering": ["lot_id", "number"],
            },
        ),
        migrations.CreateModel(
            name="FieldSegment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=40)),
                ("start_plant", models.PositiveIntegerField()),
                ("end_plant", models.PositiveIntegerField()),
                ("is_pilot", models.BooleanField(default=False)),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="campo.fieldrow",
                    ),
                ),
            ],
            options={
                "verbose_name": "segmento",
                "db_table": "field_segments",
                "ordering": ["row_id", "start_plant"],
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("INICIO", "Inicio"),
                            ("FIN", "Fin"),
                            ("INTERMEDIO", "Intermedio"),
                        ],
                        max_length=12,
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markers",
                        to="campo.fieldrow",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="markers",
                        to="campo.fieldsegment",
                    ),
                ),
            ],
            options={
                "verbose_name": "marcador",
                "verbose_name_plural": "marcadores",
                "db_table": "markers",
                "ordering": ["row_id", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="fieldrow",
            constraint=models.UniqueConstraint(
                fields=("lot", "number"), name="field_rows_lote_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_plant__lte", models.F("end_plant"))),
                name="segmento_rango",
            ),
        ),
    ]
