# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marker",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__in", ["INICIO", "FIN", "INTERMEDIO"])),
                name="markers_position_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="marker",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    ("lat__isnull", True),
                    _connector="OR",
                ),
                name="markers_lat_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="marker",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    ("lon__isnull", True),
                    _connector="OR",
                ),
                name="markers_lon_valido",
            ),
        ),
    ]
