# Generated by Django 5.2.17 on 2026-10-08 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0003_catalogo_activo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada / portón"),
                            ("ALMACEN", "Almacén"),
                            ("POZO", "Pozo / reservorio"),
                            ("REUNION", "Punto de reunión"),
                            ("OFICINA", "Oficina / caseta"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "punto del fundo",
                "verbose_name_plural": "puntos del fundo",
                "db_table": "points_of_interest",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "ENTRADA",
                                    "ALMACEN",
                                    "POZO",
                                    "REUNION",
                                    "OFICINA",
                                    "OTRO",
                                ],
                            )
                        ),
                        name="points_of_interest_kind_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lat__gte", -90), ("lat__lte", 90)),
                        name="points_of_interest_lat_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lon__gte", -180), ("lon__lte", 180)),
                        name="points_of_interest_lon_valido",
                    ),
                ],
            },
        ),
    ]
