# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente'), ('CONFIRMADO_POR_ESPECIALISTA', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('EVIDENCIA_INSUFICIENTE', 'Evidencia insuficiente')], default='PENDIENTE_REVISION', max_length=40)),
                ('notification_status', models.CharField(choices=[('SIN_AVISO', 'Sin aviso'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('ANULADO', 'Anulado')], default='SIN_AVISO', max_length=24)),
                ('disease', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('location_source', models.CharField(choices=[('GPS', 'GPS'), ('MARCADOR', 'Marcador'), ('SIN_UBICACION', 'Sin ubicacion')], default='GPS', max_length=24)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='evidencias.capture')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_cases',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente'), ('CONFIRMADO_POR_ESPECIALISTA', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('EVIDENCIA_INSUFICIENTE', 'Evidencia insuficiente')], max_length=40)),
                ('to_status', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente'), ('CONFIRMADO_POR_ESPECIALISTA', 'Confirmado'), ('DESCARTADO', 'Descartado'), ('EVIDENCIA_INSUFICIENTE', 'Evidencia insuficiente')], max_length=40)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='revision.case')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'human_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-opened_at'], name='idx_case_status_time'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_case_location'),
        ),
    ]
