# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campo", "0001_initial"),
        ("evidencias", "0001_initial"),
        ("ia", "0001_initial"),
        ("monitoreo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("IA", "Indicio sugerido por IA"),
                            ("MANUAL", "Abierto por el especialista"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_REVISION", "Pendiente de revisión"),
                            (
                                "CONFIRMADO_POR_ESPECIALISTA",
                                "Confirmado por especialista",
                            ),
                            ("DESCARTADO", "Descartado"),
                            ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                        ],
                        default="PENDIENTE_REVISION",
                        max_length=28,
                    ),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("PENDIENTE_ENVIO", "Pendiente de envío"),
                            ("ENVIADO", "Enviado"),
                            ("ERROR_ENVIO", "Error de envío"),
                        ],
                        default="NO_APLICA",
                        max_length=16,
                    ),
                ),
                ("detections_count", models.PositiveIntegerField(default=0)),
                ("max_confidence", models.FloatField(blank=True, null=True)),
                (
                    "lateral_code",
                    models.CharField(
                        choices=[
                            ("LATERAL_A", "Lateral A"),
                            ("LATERAL_B", "Lateral B"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("gps_accuracy_m", models.FloatField(blank=True, null=True)),
                (
                    "location_source",
                    models.CharField(
                        choices=[
                            ("GPS", "GPS del controlador"),
                            ("MARCADOR", "Coordenadas del marcador (aproximada)"),
                            ("NINGUNA", "Sin coordenadas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ia.aitask",
                    ),
                ),
                (
                    "capture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case",
                        to="evidencias.capture",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campo.fieldlot",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campo.marker",
                    ),
                ),
                (
                    "monitoring_pass",
                    models.ForeignKey(
                        db_column="pass_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="monitoreo.monitoringpass",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campo.fieldrow",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campo.fieldsegment",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="monitoreo.capturesequence",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="monitoreo.monitoringsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "caso",
                "db_table": "review_cases",
            },
        ),
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            (
                                "CONFIRMADO_POR_ESPECIALISTA",
                                "Confirmado por especialista",
                            ),
                            ("DESCARTADO", "Descartado"),
                            ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                        ],
                        max_length=28,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("confirmed_class", models.CharField(blank=True, max_length=60)),
                ("rejected_detection_ids", models.JSONField(blank=True, default=list)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("correction_reason", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "ai_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ia.aitask",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="revision.case",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="revision.humanreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "decisión del especialista",
                "verbose_name_plural": "decisiones del especialista",
                "db_table": "human_reviews",
                "ordering": ["reviewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status", "opened_at"], name="caso_bandeja_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["lot", "row", "status"], name="caso_plano_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["captured_at"], name="caso_fecha_idx"),
        ),
        migrations.AddConstraint(
            model_name="humanreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("case",),
                name="una_decision_vigente_por_caso",
            ),
        ),
    ]
