# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0002_restricciones_check"),
        ("evidencias", "0002_restricciones_check"),
        ("ia", "0002_restricciones_check"),
        ("monitoreo", "0002_restricciones_check"),
        ("revision", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["IA", "MANUAL"])),
                name="review_cases_origin_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDIENTE_REVISION",
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                        ],
                    )
                ),
                name="review_cases_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "notification_status__in",
                        ["NO_APLICA", "PENDIENTE_ENVIO", "ENVIADO", "ERROR_ENVIO"],
                    )
                ),
                name="review_cases_notification_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("max_confidence__gte", 0), ("max_confidence__lte", 1)),
                    ("max_confidence__isnull", True),
                    _connector="OR",
                ),
                name="review_cases_max_confidence_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(("lateral_code__in", ["LATERAL_A", "LATERAL_B"])),
                name="review_cases_lateral_code_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    ("lat__isnull", True),
                    _connector="OR",
                ),
                name="review_cases_lat_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    ("lon__isnull", True),
                    _connector="OR",
                ),
                name="review_cases_lon_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gps_accuracy_m__gte", 0),
                    ("gps_accuracy_m__isnull", True),
                    _connector="OR",
                ),
                name="review_cases_gps_accuracy_m_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("location_source__in", ["GPS", "MARCADOR", "NINGUNA"])
                ),
                name="review_cases_location_source_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="humanreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision__in",
                        [
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                        ],
                    )
                ),
                name="human_reviews_decision_valido",
            ),
        ),
    ]
