# Generated by Django 5.2.17 on 2026-10-08 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0003_catalogo_activo"),
        ("evidencias", "0002_restricciones_check"),
        ("ia", "0003_umbral_auto_y_estados_v13"),
        ("monitoreo", "0002_restricciones_check"),
        ("revision", "0002_restricciones_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="case",
            name="review_cases_status_valido",
        ),
        migrations.RemoveConstraint(
            model_name="humanreview",
            name="human_reviews_decision_valido",
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_REVISION", "Pendiente de revisión"),
                    ("CONFIRMADO_POR_ESPECIALISTA", "Confirmado por especialista"),
                    ("DESCARTADO", "Descartado"),
                    ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                    ("CONFIRMADO_POR_IA", "Confirmado por IA"),
                    ("POSIBLE_PLAGA", "Posible plaga"),
                ],
                default="PENDIENTE_REVISION",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="humanreview",
            name="decision",
            field=models.CharField(
                choices=[
                    ("CONFIRMADO_POR_ESPECIALISTA", "Confirmado por especialista"),
                    ("POSIBLE_PLAGA", "Posible plaga"),
                    ("DESCARTADO", "Descartado"),
                    ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                ],
                max_length=28,
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDIENTE_REVISION",
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                            "CONFIRMADO_POR_IA",
                            "POSIBLE_PLAGA",
                        ],
                    )
                ),
                name="review_cases_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="humanreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision__in",
                        [
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "POSIBLE_PLAGA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                        ],
                    )
                ),
                name="human_reviews_decision_valido",
            ),
        ),
    ]
