# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('model_config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('weights_ref', models.CharField(blank=True, max_length=255)),
                ('conf_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_configs',
                'ordering': ['-is_active', 'name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TOMADA', 'Tomada'), ('INDICIO_SUGERIDO_POR_IA', 'Indicio sugerido'), ('SIN_INDICIOS', 'Sin indicios'), ('ERROR', 'Error')], default='PENDIENTE', max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=120)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task', to='evidencias.capture')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ia.modelconfig')),
            ],
            options={
                'db_table': 'ai_tasks',
                'ordering': ['requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bbox', models.JSONField(default=dict)),
                ('review_status', models.CharField(choices=[('SIN_REVISION', 'Sin revision'), ('CONFIRMADO', 'Confirmado'), ('DESCARTADO', 'Descartado')], default='SIN_REVISION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='ia.aitask')),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['status', 'available_at'], name='idx_ai_task_queue'),
        ),
    ]
