# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidencias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("version", models.CharField(max_length=40, unique=True)),
                ("weights_uri", models.CharField(max_length=255)),
                ("weights_sha256", models.CharField(blank=True, max_length=64)),
                ("classes", models.JSONField(default=list)),
                ("conf_threshold", models.FloatField(default=0.25)),
                ("iou_threshold", models.FloatField(default=0.45)),
                ("imgsz", models.PositiveIntegerField(default=640)),
                ("tiling", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "modelo de IA",
                "verbose_name_plural": "modelos de IA",
                "db_table": "model_configs",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("active",),
                        name="un_solo_modelo_activo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_DE_ANALISIS", "Pendiente de análisis"),
                            ("EN_ANALISIS", "En análisis"),
                            ("INDICIO_SUGERIDO_POR_IA", "Indicio sugerido por IA"),
                            ("SIN_INDICIOS_IA", "Sin indicios de la IA"),
                            ("ERROR_DE_ANALISIS", "Error de análisis"),
                        ],
                        default="PENDIENTE_DE_ANALISIS",
                        max_length=24,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=80)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("processing_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("model_version", models.CharField(blank=True, max_length=40)),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("raw_output", models.JSONField(blank=True, null=True)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_tasks",
                        to="evidencias.capture",
                    ),
                ),
                (
                    "model_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="ia.modelconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea de IA",
                "verbose_name_plural": "tareas de IA",
                "db_table": "ai_tasks",
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=60)),
                ("confidence", models.FloatField()),
                ("x_min", models.FloatField()),
                ("y_min", models.FloatField()),
                ("x_max", models.FloatField()),
                ("y_max", models.FloatField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_REVISION", "Pendiente de revisión"),
                            ("CONFIRMADO_POR_ESPECIALISTA", "Confirmada"),
                            ("DESCARTADO", "Descartada"),
                            ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                        ],
                        default="PENDIENTE_REVISION",
                        max_length=28,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="ia.aitask",
                    ),
                ),
            ],
            options={
                "verbose_name": "caja",
                "db_table": "detections",
                "ordering": ["-confidence"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0), ("confidence__lte", 1)
                        ),
                        name="det_confianza",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("x_min__lt", models.F("x_max")),
                            ("y_min__lt", models.F("y_max")),
                        ),
                        name="det_caja",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(fields=["status", "available_at"], name="ai_cola_idx"),
        ),
        migrations.AddConstraint(
            model_name="aitask",
            constraint=models.UniqueConstraint(
                fields=("capture", "model_config"), name="ai_task_por_modelo"
            ),
        ),
    ]
