# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0002_restricciones_check"),
        ("ia", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aitask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDIENTE_DE_ANALISIS",
                            "EN_ANALISIS",
                            "INDICIO_SUGERIDO_POR_IA",
                            "SIN_INDICIOS_IA",
                            "ERROR_DE_ANALISIS",
                        ],
                    )
                ),
                name="ai_tasks_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="detection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        [
                            "PENDIENTE_REVISION",
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                        ],
                    )
                ),
                name="detections_review_status_valido",
            ),
        ),
    ]
