# Generated by Django 5.2.17 on 2026-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0002_restricciones_check"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detection",
            name="detections_review_status_valido",
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="auto_confirm_threshold",
            field=models.FloatField(
                blank=True,
                help_text="Ej.: 0.70. Vacío = apagado. Solo con un modelo validado con fotos del fundo.",
                null=True,
                verbose_name="umbral de confirmación automática",
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_REVISION", "Pendiente de revisión"),
                    ("CONFIRMADO_POR_ESPECIALISTA", "Confirmada"),
                    ("DESCARTADO", "Descartada"),
                    ("EVIDENCIA_INSUFICIENTE", "Evidencia insuficiente"),
                    ("CONFIRMADO_POR_IA", "Confirmada por IA"),
                    ("POSIBLE_PLAGA", "Posible plaga"),
                ],
                default="PENDIENTE_REVISION",
                max_length=28,
            ),
        ),
        migrations.AddConstraint(
            model_name="detection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        [
                            "PENDIENTE_REVISION",
                            "CONFIRMADO_POR_ESPECIALISTA",
                            "DESCARTADO",
                            "EVIDENCIA_INSUFICIENTE",
                            "CONFIRMADO_POR_IA",
                            "POSIBLE_PLAGA",
                        ],
                    )
                ),
                name="detections_review_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_confirm_threshold__isnull", True),
                    models.Q(
                        ("auto_confirm_threshold__gt", 0),
                        ("auto_confirm_threshold__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="model_configs_umbral_auto_valido",
            ),
        ),
    ]
