# Generated by Django 5.2.17 on 2026-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0002_restricciones_check"),
        ("ia", "0003_umbral_auto_y_estados_v13"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aitask",
            name="ai_tasks_status_valido",
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="review_threshold",
            field=models.FloatField(
                blank=True,
                help_text="Ej.: 0.50. Por debajo, la IA descarta la foto sola (no abre caso). Vacío = apagado.",
                null=True,
                verbose_name="umbral de revisión",
            ),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_DE_ANALISIS", "Pendiente de análisis"),
                    ("EN_ANALISIS", "En análisis"),
                    ("INDICIO_SUGERIDO_POR_IA", "Indicio sugerido por IA"),
                    ("SIN_INDICIOS_IA", "Sin indicios de la IA"),
                    ("DESCARTADO_POR_IA", "Descartado por la IA"),
                    ("ERROR_DE_ANALISIS", "Error de análisis"),
                ],
                default="PENDIENTE_DE_ANALISIS",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="aitask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDIENTE_DE_ANALISIS",
                            "EN_ANALISIS",
                            "INDICIO_SUGERIDO_POR_IA",
                            "SIN_INDICIOS_IA",
                            "DESCARTADO_POR_IA",
                            "ERROR_DE_ANALISIS",
                        ],
                    )
                ),
                name="ai_tasks_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review_threshold__isnull", True),
                    models.Q(("review_threshold__gt", 0), ("review_threshold__lte", 1)),
                    _connector="OR",
                ),
                name="model_configs_umbral_revision_valido",
            ),
        ),
    ]
