# Generated by Django 5.2.17 on 2026-10-05 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campo", "0001_initial"),
        ("cuentas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringPass",
            fields=[
                ("pass_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "lateral_code",
                    models.CharField(
                        choices=[
                            ("LATERAL_A", "Lateral A"),
                            ("LATERAL_B", "Lateral B"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pass_order", models.PositiveIntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("ASCENDENTE", "Ascendente"),
                            ("DESCENDENTE", "Descendente"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Lista"),
                            ("ACTIVE", "En curso"),
                            ("PAUSED", "En pausa"),
                            ("COMPLETED", "Completa"),
                            ("INCOMPLETE", "Incompleta"),
                        ],
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("sequences_total", models.PositiveIntegerField(default=0)),
                ("sequences_complete", models.PositiveIntegerField(default=0)),
                ("sequences_incomplete", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "end_marker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.marker",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="campo.fieldlot",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passes",
                        to="campo.fieldrow",
                    ),
                ),
                (
                    "start_marker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.marker",
                    ),
                ),
            ],
            options={
                "verbose_name": "pasada",
                "db_table": "monitoring_passes",
            },
        ),
        migrations.CreateModel(
            name="MarkerChange",
            fields=[
                (
                    "marker_change_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("changed_at", models.DateTimeField()),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("gps_accuracy_m", models.FloatField(blank=True, null=True)),
                ("gps_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "marker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.marker",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.fieldsegment",
                    ),
                ),
                (
                    "monitoring_pass",
                    models.ForeignKey(
                        db_column="pass_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marker_changes",
                        to="monitoreo.monitoringpass",
                    ),
                ),
            ],
            options={
                "db_table": "marker_changes",
            },
        ),
        migrations.CreateModel(
            name="CaptureSequence",
            fields=[
                ("sequence_id", models.UUIDField(primary_key=True, serialize=False)),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTOMATICO", "Automático"),
                            ("MIXTO", "Mixto"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Creada"),
                            ("COMMAND_SENT", "Orden enviada"),
                            ("PARTIAL", "Parcial"),
                            ("COMPLETE", "Completa"),
                            ("INCOMPLETE", "Incompleta"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        max_length=14,
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("gps_accuracy_m", models.FloatField(blank=True, null=True)),
                ("gps_timestamp", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expected_capture_ids", models.JSONField(default=dict)),
                ("slot_outcomes", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.marker",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campo.fieldsegment",
                    ),
                ),
                (
                    "monitoring_pass",
                    models.ForeignKey(
                        db_column="pass_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="monitoreo.monitoringpass",
                    ),
                ),
            ],
            options={
                "verbose_name": "secuencia",
                "db_table": "capture_sequences",
            },
        ),
        migrations.CreateModel(
            name="MonitoringSession",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PREPARING", "Preparando"),
                            ("READY", "Lista"),
                            ("ACTIVE", "En curso"),
                            ("PAUSED", "En pausa"),
                            ("CLOSING", "Cerrando"),
                            ("CLOSED", "Cerrada"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTOMATICO", "Automático"),
                            ("MIXTO", "Mixto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("interval_ms", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("app_version", models.CharField(max_length=40)),
                ("config_version", models.CharField(max_length=40)),
                ("quality_profile_version", models.CharField(max_length=20)),
                ("short_test_passed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "controller_device",
                    models.ForeignKey(
                        db_column="controller_device_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="cuentas.device",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        db_column="operator_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión de monitoreo",
                "verbose_name_plural": "sesiones de monitoreo",
                "db_table": "monitoring_sessions",
            },
        ),
        migrations.AddField(
            model_name="monitoringpass",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passes",
                to="monitoreo.monitoringsession",
            ),
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("incident_id", models.UUIDField(primary_key=True, serialize=False)),
                ("capture_id", models.UUIDField(blank=True, null=True)),
                ("device_id", models.UUIDField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CALIDAD", "Calidad"),
                            ("DESCONEXION", "Desconexión"),
                            ("BATERIA", "Batería"),
                            ("TEMPERATURA", "Temperatura"),
                            ("ESPACIO", "Espacio"),
                            ("GPS", "GPS"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("SINCRONIZACION", "Sincronización"),
                            ("SOPORTE", "Soporte"),
                            ("OPERADOR", "Operador"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("AVISO", "Aviso"),
                            ("ERROR", "Error"),
                        ],
                        max_length=6,
                    ),
                ),
                ("detail", models.TextField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "created_by",
                    models.CharField(
                        choices=[("SISTEMA", "Sistema"), ("OPERADOR", "Operador")],
                        max_length=10,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="monitoreo.capturesequence",
                    ),
                ),
                (
                    "monitoring_pass",
                    models.ForeignKey(
                        blank=True,
                        db_column="pass_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="monitoreo.monitoringpass",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="monitoreo.monitoringsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "incidencia",
                "db_table": "incidents",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="capturesequence",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="monitoreo.monitoringsession",
            ),
        ),
        migrations.CreateModel(
            name="SessionDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CAMERA_1", "Cámara 1"), ("CAMERA_2", "Cámara 2")],
                        max_length=10,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=10
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=80)),
                ("os_version", models.CharField(blank=True, max_length=40)),
                ("app_version", models.CharField(blank=True, max_length=40)),
                ("paired_at", models.DateTimeField()),
                ("released", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cuentas.device",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="monitoreo.monitoringsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_devices",
            },
        ),
        migrations.AddIndex(
            model_name="monitoringsession",
            index=models.Index(fields=["started_at"], name="sesion_inicio_idx"),
        ),
        migrations.AddIndex(
            model_name="monitoringpass",
            index=models.Index(
                fields=["row", "lateral_code", "status"], name="pasada_cobertura_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.UniqueConstraint(
                fields=("monitoring_pass", "sequence_number"),
                name="secuencia_numero_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessiondevice",
            constraint=models.UniqueConstraint(
                fields=("session", "role", "device"), name="session_devices_unico"
            ),
        ),
    ]
