# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('crop', models.CharField(default='Vid', max_length=80)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('geojson', models.JSONField(blank=True, default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='monitoreo.farm')),
            ],
            options={
                'db_table': 'lots',
                'ordering': ['farm__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CropRow',
            fields=[
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=40)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='monitoreo.lot')),
            ],
            options={
                'db_table': 'crop_rows',
                'ordering': ['lot__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('SINCRONIZADA', 'Sincronizada'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='monitoreo.lot')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldPass',
            fields=[
                ('pass_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=40)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='monitoreo.croprow')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='monitoreo.monitoringsession')),
            ],
            options={
                'db_table': 'field_passes',
                'ordering': ['session', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionCamera',
            fields=[
                ('camera_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('IZQUIERDA', 'Izquierda'), ('DERECHA', 'Derecha'), ('FRONTAL', 'Frontal')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.mobiledevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitoreo.monitoringsession')),
            ],
            options={
                'db_table': 'session_cameras',
            },
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='uniq_lot_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='croprow',
            constraint=models.UniqueConstraint(fields=('lot', 'number'), name='uniq_row_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='sessioncamera',
            constraint=models.UniqueConstraint(fields=('session', 'side'), name='uniq_camera_side_per_session'),
        ),
    ]
