# Generated by Django 5.2.17 on 2026-10-05 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campo", "0002_restricciones_check"),
        ("cuentas", "0002_restricciones_check"),
        ("monitoreo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["MANUAL", "AUTOMATICO", "MIXTO"])),
                name="capture_sequences_mode_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "CREATED",
                            "COMMAND_SENT",
                            "PARTIAL",
                            "COMPLETE",
                            "INCOMPLETE",
                            "CANCELLED",
                        ],
                    )
                ),
                name="capture_sequences_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    ("lat__isnull", True),
                    _connector="OR",
                ),
                name="capture_sequences_lat_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    ("lon__isnull", True),
                    _connector="OR",
                ),
                name="capture_sequences_lon_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gps_accuracy_m__gte", 0),
                    ("gps_accuracy_m__isnull", True),
                    _connector="OR",
                ),
                name="capture_sequences_gps_accuracy_m_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "CALIDAD",
                            "DESCONEXION",
                            "BATERIA",
                            "TEMPERATURA",
                            "ESPACIO",
                            "GPS",
                            "TRANSFERENCIA",
                            "SINCRONIZACION",
                            "SOPORTE",
                            "OPERADOR",
                            "OTRO",
                        ],
                    )
                ),
                name="incidents_type_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity__in", ["INFO", "AVISO", "ERROR"])),
                name="incidents_severity_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.CheckConstraint(
                condition=models.Q(("created_by__in", ["SISTEMA", "OPERADOR"])),
                name="incidents_created_by_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="markerchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lat__gte", -90), ("lat__lte", 90)),
                    ("lat__isnull", True),
                    _connector="OR",
                ),
                name="marker_changes_lat_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="markerchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lon__gte", -180), ("lon__lte", 180)),
                    ("lon__isnull", True),
                    _connector="OR",
                ),
                name="marker_changes_lon_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="markerchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gps_accuracy_m__gte", 0),
                    ("gps_accuracy_m__isnull", True),
                    _connector="OR",
                ),
                name="marker_changes_gps_accuracy_m_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringpass",
            constraint=models.CheckConstraint(
                condition=models.Q(("lateral_code__in", ["LATERAL_A", "LATERAL_B"])),
                name="monitoring_passes_lateral_code_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringpass",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["ASCENDENTE", "DESCENDENTE"])),
                name="monitoring_passes_direction_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringpass",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["READY", "ACTIVE", "PAUSED", "COMPLETED", "INCOMPLETE"],
                    )
                ),
                name="monitoring_passes_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "PREPARING",
                            "READY",
                            "ACTIVE",
                            "PAUSED",
                            "CLOSING",
                            "CLOSED",
                        ],
                    )
                ),
                name="monitoring_sessions_status_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["MANUAL", "AUTOMATICO", "MIXTO"])),
                name="monitoring_sessions_mode_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessiondevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["CAMERA_1", "CAMERA_2"])),
                name="session_devices_role_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessiondevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform__in", ["android", "ios"])),
                name="session_devices_platform_valido",
            ),
        ),
    ]
